package:
  name: leafcutter
  version: 2.0.2

source:
  git_url: https://github.com/davidaknowles/leafcutter.git
  git_tag: leafcutter2

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy>=1.21

  run:
    - python
    - pytorch # -c pytorch
    - pyro-ppl # -c conda-forge
    - scipy>=1.11
    - pandas
    - scikit-learn
    - numpy>=1.21

about:
  home: 
  license: GPL (>= 3)
  summary: Alternative Splicing Quantification, Differential Splicing and Splicing QTL Mapping
  license_family: GPL3
